using System.Text.Json.Serialization;

namespace BugTriageWorkflow.Models;

/// <summary>
/// Represents the classification result generated by the AI agent.
/// This structured output is used to determine routing decisions.
/// </summary>
public class BugClassification {
    /// <summary>
    /// High-level category assigned to the bug report.
    /// Examples: frontend, backend, infrastructure, unknown.
    /// </summary>
    [JsonPropertyName("category")]
    public string Category { get; set; } = "";

    /// <summary>
    /// Probability distribution for the category classification.
    /// Order:
    /// [frontend, backend, infrastructure, unknown]
    /// Values should sum to approximately 1.0.
    /// </summary>
    [JsonPropertyName("category_vector")]
    public List<double> CategoryVector { get; set; } = [];

    /// <summary>
    /// Estimated impact and severity of the reported issue.
    /// Examples: low, medium, high.
    /// </summary>
    [JsonPropertyName("urgency")]
    public string Urgency { get; set; } = "";

    /// <summary>
    /// Numeric urgency value used for evaluation.
    /// Expected mapping:
    /// low = 0.0
    /// medium = 0.5
    /// high = 1.0
    /// </summary>
    [JsonPropertyName("urgency_value")]
    public double UrgencyValue { get; set; }

    /// <summary>
    /// Additional information the agent believes is required
    /// to properly investigate or reproduce the issue.
    /// </summary>
    [JsonPropertyName("missing_info")]
    public List<string> MissingInfo { get; set; } = [];

    /// <summary>
    /// Suggested destination for the bug report.
    /// Examples: frontend_team, backend_team,
    /// infrastructure_team, human_review.
    /// </summary>
    [JsonPropertyName("recommended_route")]
    public string RecommendedRoute { get; set; } = "";

    /// <summary>
    /// Probability distribution for the routing decision.
    /// Order:
    /// [frontend_team, backend_team, infrastructure_team, human_review]
    /// Values should sum to approximately 1.0.
    /// </summary>
    [JsonPropertyName("recommended_route_vector")]
    public List<double> RecommendedRouteVector { get; set; } = [];

    /// <summary>
    /// Indicates whether the bug report should be escalated
    /// for manual review by a human.
    /// </summary>
    [JsonPropertyName("escalate_to_human")]
    public bool EscalateToHuman { get; set; }

    /// <summary>
    /// Numeric representation of the escalation decision.
    /// Expected mapping:
    /// false = 0.0
    /// true = 1.0
    /// </summary>
    [JsonPropertyName("escalate_to_human_value")]
    public double EscalateToHumanValue { get; set; }

    /// <summary>
    /// Indicates whether the supplied evidence supports,
    /// contradicts, or is inconclusive regarding the report.
    /// </summary>
    [JsonPropertyName("verification_status")]
    public string VerificationStatus { get; set; } = "";

    /// <summary>
    /// Probability distribution for the verification decision.
    /// Order:
    /// [supported_by_evidence, contradicted_by_evidence, inconclusive]
    /// Values should sum to approximately 1.0.
    /// </summary>
    [JsonPropertyName("verification_status_vector")]
    public List<double> VerificationStatusVector { get; set; } = [];

    /// <summary>
    /// The estimated likelihood that the report may be inaccurate
    /// or unsupported by the available evidence.
    /// Examples: low, medium, high.
    /// </summary>
    [JsonPropertyName("false_report_risk")]
    public string FalseReportRisk { get; set; } = "";

    /// <summary>
    /// Numeric representation of the false report risk.
    /// Expected mapping:
    /// low = 0.0
    /// medium = 0.5
    /// high = 1.0
    /// </summary>
    [JsonPropertyName("false_report_risk_value")]
    public double FalseReportRiskValue { get; set; }

    /// <summary>
    /// Human-readable explanation describing why the agent
    /// assigned the verification status and false report risk.
    /// </summary>
    [JsonPropertyName("verification_reason")]
    public string VerificationReason { get; set; } = "";
}